version: 0.2

phases:
  install:
    commands:
      # Install NodeJS
      - curl --silent --location https://rpm.nodesource.com/setup_10.x | bash -
      - yum install nodejs
      # Setup for Yarn
      - curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
      - rpm --import https://dl.yarnpkg.com/rpm/pubkey.gpg
      - yum install yarn
      - yarn --version
      # Run yarn install 
      - yarn install
  build:
    commands:
      - yarn build

artifacts:
  files:
    - '**/*'
  base-directory: dist