version: 0.2

phases:
  install:
    commands:
      # Install NodeJS
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
      - . ~/.nvm/nvm.sh
      - node -e "console.log('Running Node.js ' + process.version)"
      # Setup for Yarn
      - curl -o- -L https://yarnpkg.com/install.sh | bash
      - yarn --version
      # Run yarn install 
      - yarn install
  build:
    commands:
      - yarn build

artifacts:
  files:
    - '**/*'
  base-directory: dist